---
# Standards: 0.2
dependency:
  name: galaxy
  requirements_file: requirements.yml
driver:
  name: docker
docker:
  containers:
    - name: base-java8-centos
      image: milcom/centos7-systemd
      image_version: latest
      ansible_groups:
        - group1
    - name: base-java8-ubuntu
      image: ubuntu
      image_version: latest
      ansible_groups:
        - group2
verifier:
  name: goss
