---

dependency:
  name: galaxy
  requirements_file: requirements.yml
driver:
  name: docker
verifier:
  name: goss
  lint:
    name: yamllint
platforms:
  - name: base-maven-centos7
    image: centos:7
    privileged: True
  - name: base-maven-centos6
    image: centos:6
    privileged: true
  - name: base-maven-ubuntu
    image: ubuntu:xenial
    privileged: True
provisioner:
  name: ansible
  config_options:
    defaults:
      remote_tmp: /tmp
  playbooks:
    converge: playbook.yml
  lint:
    name: ansible-lint
scenario:
  name: default
