---

dependency:
  name: galaxy
  requirements_file: requirements.yml
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: base-maven-centos7
    image: milcom/centos7-systemd
    privileged: true
  - name: base-maven-ubuntu
    image: ubuntu:xenial
    privileged: true
provisioner:
  name: ansible
verifier:
  name: ansible
